project_name: testkube-operator
builds:
  - id: "linux"
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-operator:{{ .Branch }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"

release:
  disable: true
