apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: webhook-admission
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-tests-testkube-io-v1-testtrigger
    failurePolicy: Fail
    name: vtesttrigger.kb.io
    rules:
      - apiGroups:
          - tests.testkube.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - testtriggers
    sideEffects: None

