---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - executor.testkube.io
  resources:
  - executors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - executor.testkube.io
  resources:
  - executors/finalizers
  verbs:
  - update
- apiGroups:
  - executor.testkube.io
  resources:
  - executors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - executor.testkube.io
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - executor.testkube.io
  resources:
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - executor.testkube.io
  resources:
  - webhooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - tests/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - tests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuites/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testtriggers/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - testtriggers/status
  verbs:
  - get
  - patch
  - update
