---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - executor.testkube.io
  resources:
  - executors
  - webhooks
  - webhooktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - executor.testkube.io
  resources:
  - executors/finalizers
  - webhooks/finalizers
  - webhooktemplates/finalizers
  verbs:
  - update
- apiGroups:
  - executor.testkube.io
  resources:
  - executors/status
  - webhooks/status
  - webhooktemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts
  - templates
  - testexecutions
  - tests
  - testsources
  - testsuiteexecutions
  - testsuites
  - testtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts/finalizers
  - templates/finalizers
  - testexecutions/finalizers
  - tests/finalizers
  - testsources/finalizers
  - testsuiteexecutions/finalizers
  - testsuites/finalizers
  - testtriggers/finalizers
  verbs:
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - scripts/status
  - testexecutions/status
  - tests/status
  - testsources/status
  - testsuiteexecutions/status
  - testsuites/status
  - testtriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tests.testkube.io
  resources:
  - templates/status
  verbs:
  - get
- apiGroups:
  - testworkflows.testkube.io
  resources:
  - testworkflowexecutions
  - testworkflows
  - testworkflowtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testworkflows.testkube.io
  resources:
  - testworkflowexecutions/finalizers
  - testworkflows/finalizers
  - testworkflowtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - testworkflows.testkube.io
  resources:
  - testworkflowexecutions/status
  - testworkflows/status
  verbs:
  - get
  - patch
  - update
