# permissions for end users to view testsuiteexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsuiteexecution-viewer-role
rules:
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuiteexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsuiteexecutions/status
  verbs:
  - get
