# permissions for end users to view testworkflowexecutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testworkflowexecution-viewer-role
rules:
- apiGroups:
  - tests.testkube.io
  resources:
  - testworkflowexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testworkflowexecutions/status
  verbs:
  - get
