# permissions for end users to edit testsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsource-editor-role
rules:
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources/status
  verbs:
  - get
