# permissions for end users to view testsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testsource-viewer-role
rules:
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tests.testkube.io
  resources:
  - testsources/status
  verbs:
  - get
