# permissions for end users to view webhook templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhooktemplate-viewer-role
rules:
- apiGroups:
  - executor.testkube.io
  resources:
  - webhooktemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - executor.testkube.io
  resources:
  - webhooktemplates/status
  verbs:
  - get
