apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-sample
spec:
  # Add fields here
  type: postman/collection
  content:
    type: file-string
    data: >
        {
        "info": {
            "_postman_id": "fa1ce97f-ff5d-40ed-9c9c-e0a92063ce98",
            "name": "Remotes",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "item": [
            {
            "name": "Google",
            "event": [
                {
                "listen": "test",
                "script": {
                    "exec": [
                    "    pm.test(\"Successful GET request\", function () {",
                    "        pm.expect(pm.response.code).to.be.oneOf([200, 201, 202]);",
                    "    });"
                    ],
                    "type": "text/javascript"
                }
                }
            ],
            "request": {
                "method": "GET",
                "header": [],
                "url": {
                "raw": "https://google.com",
                "protocol": "https",
                "host": [
                    "google",
                    "com"
                ]
                }
            },
            "response": []
            },
            {
            "name": "Kasia.in Homepage",
            "event": [
                {
                "listen": "test",
                "script": {
                    "exec": [
                    "pm.test(\"Body matches string\", function () {",
                    "    pm.expect(pm.response.text()).to.include(\"PRZEPIS NA CHLEB\");",
                    "});"
                    ],
                    "type": "text/javascript"
                }
                }
            ],
            "request": {
                "method": "GET",
                "header": [],
                "url": {
                "raw": "https://kasia.in",
                "protocol": "https",
                "host": [
                    "kasia",
                    "in"
                ]
                }
            },
            "response": []
            }
        ]
        }

