env:
  # Goreleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}
  # Setup to enable Docker to use, e.g., the GitHub actions cache; see
  # https://docs.docker.com/build/building/cache/backends/
  # https://github.com/moby/buildkit#export-cache
  - DOCKER_BUILDX_CACHE_FROM={{ if index .Env "DOCKER_BUILDX_CACHE_FROM"  }}{{ .Env.DOCKER_BUILDX_CACHE_FROM }}{{ else }}type=registry{{ end }}
  - DOCKER_BUILDX_CACHE_TO={{ if index .Env "DOCKER_BUILDX_CACHE_TO"  }}{{ .Env.DOCKER_BUILDX_CACHE_TO }}{{ else }}type=inline{{ end }}

project_name: testkube-operator
builds:
  - id: "linux"
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-operator:{{ .ShortCommit }}-amd64"
      - "kubeshop/testkube-operator:{{ .Version }}-amd64"
      - "kubeshop/testkube-operator:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
      - "--build-arg=ALPINE_IMAGE={{ .Env.ALPINE_IMAGE }}"

  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-operator:{{ .ShortCommit }}-arm64v8"
      - "kubeshop/testkube-operator:{{ .Version }}-arm64v8"
      - "kubeshop/testkube-operator:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

docker_manifests:
  - name_template: kubeshop/testkube-operator:{{ .ShortCommit }}
    image_templates:
      - kubeshop/testkube-operator:{{ .ShortCommit }}-amd64
      - kubeshop/testkube-operator:{{ .ShortCommit }}-arm64v8
  - name_template: kubeshop/testkube-operator:{{ .Version }}
    image_templates:
      - kubeshop/testkube-operator:{{ .Version }}-amd64
      - kubeshop/testkube-operator:{{ .Version }}-arm64v8
  - name_template: kubeshop/testkube-operator:latest
    image_templates:
      - kubeshop/testkube-operator:latest-amd64
      - kubeshop/testkube-operator:latest-arm64v8

release:
  disable: true
