name: Remove sandbox environment

permissions:
  contents: read
  actions: write

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    if: startsWith(github.event.pull_request.head.ref, 'sandbox/')
    name: Pass payload data
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: kubeshop/testkube-deployment
          event-type: sandbox_env_delete
          client-payload: '{"ref_name": "${{ github.event.pull_request.head.ref }}"}'

